ifeq ($(ANDROID_BUILD_TOP),)
	ANDROID_BUILD_TOP := $(srctree)/..
endif

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel-5.10/include
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel-5.10/include/uapi/
EXTRA_CFLAGS +=	-I$(ANDROID_BUILD_TOP)/kernel-5.10/drivers/power/supply \
		-I$(ANDROID_BUILD_TOP)/kernel-5.10/drivers/power/cps4038_mmi \

obj-$(CONFIG_CPS4038_MMI) += cps4038_mmi.o
cps4038_mmi-objs += moto_wls_auth2.0.o
cps4038_mmi-objs += wls_charger_cps4038.o
