ifeq ($(ANDROID_BUILD_TOP),)
ANDROID_BUILD_TOP := $(srctree)/..
endif

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel-5.10/include
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel-5.10/include \
		-I$(ANDROID_BUILD_TOP)/kernel-5.10/drivers/power/supply \
		-I$(ANDROID_BUILD_TOP)/kernel-5.10/drivers/power/smart_battery


obj-$(CONFIG_SMART_BATTERY) += smart_battery.o
smart_battery-objs += smart_battery_core.o
