ifeq ($(ANDROID_BUILD_TOP),)
ANDROID_BUILD_TOP := $(srctree)/..
endif

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel-5.10/include
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel-5.10/drivers/power/mmi_gauge_class

obj-$(CONFIG_MMI_GAUGE_CLASS) += mmi_gauge_class.o
