# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/

obj-$(CONFIG_MMI_GAUGE_CLASS)	+= mmi_gauge_class/
obj-$(CONFIG_NFG1000_FG_MMI)	+= nfg1000_fg_mmi/
obj-$(CONFIG_QPNP_ADAPTIVE_CHARGE)	+= qpnp_adaptive_charge/
obj-$(CONFIG_SMART_BATTERY)	+= smart_battery/
obj-$(CONFIG_BQ25980_MMI)	+= bq25980_mmi/
