ifeq ($(ANDROID_BUILD_TOP),)
	ANDROID_BUILD_TOP := $(srctree)/..
endif

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel-5.10/include
EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel-5.10/include \
		-I$(ANDROID_BUILD_TOP)/kernel-5.10/drivers/power/supply

EXTRA_CFLAGS += -I$(ANDROID_BUILD_TOP)/kernel-5.10/drivers/power/nfg1000_fg_mmi

obj-$(CONFIG_NFG1000_FG_MMI) += nfg1000_fg_mmi.o
